### ISSUE TITLE
error nprinting-adsync

### ISSUE THREAD

**Issue by bra1438** [qlik-oss/nprinting-adsync#2]
I have this error when i run the script 

ADSyncDemoApp.exe -u ...\.... -p ....
Performing a full sync.
System.DirectoryServices.DirectoryServicesCOMException (0x80072030): There is no
 such object on the server.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne
)
   at System.DirectoryServices.DirectorySearcher.FindAll()
   at ADSyncCSharp.Service.FullSyncOperation.execute(String querySearchFilter, I
EntryProcessor`1 entryProcessor)
   at ADSyncCSharp.Service.ActiveDirectorySyncService.FullSync()
   at ADSyncDemoApp.Component.AdSync.Sync()
   at ADSyncDemoApp.Program.Main(String[] args)

---
I check my Active Directory and Nprinting configuration in adsyncnprinting.config file , the syntax and the configuration is correct

Thank you for your help

**Comment by vus-qlik** [comment]
What search filter have you configured? Have you checked if it is a valid Active Directory Query?

**Comment by bra1438** [comment]
yes i checked, and i created group in my AD (the name is NPrinting)

and my searchFilter is 
add key="searchFilter" value="(&amp;(objectCategory=group)(name=NP*))"/

Below my adsyncnprinting.config file :

  
  <add key="url" value=".....:389" />

  
  <add key="domainName" value="...." />
  
  
  <add key="rootDN" value="OU=Users,DC=....,DC=...." />

  
  <add key="syncBaseDN" value="DC=....,DC=...." />

  
  
  
  <add key="searchFilter" value="(&amp;(objectCategory=group)(name=NP*))"/>
  
  
  
  <add key="searchDeletedObjectsFilter" value="(&amp;(&amp;(objectClass=group)(lastKnownParent={0}))(isDeleted=TRUE))"/>

  

  
  <add key="npUrl" value="https://....:4993" />

</appSettings>

**Comment by bra1438** [comment]
I change the group name in AD to "NPrinting_NewsStand User" and i have the same problem !!!

**Comment by vus-qlik** [comment]
Looking at the error it  seems the problem lays in the path to the domain controller 
In adsyncnprinting.config these path are configured with the following properties: 
rootDN = <root of the directory tree, e.g. DC=yourdomain,DC=com>
syncBaseDN = <pointer to the subtree containing all groups: e.g. OU=NPrinting,DC=yourdomain,DC=com>

**Comment by bra1438** [comment]
yes i checked several times, but still the same problem, i run all the steps like the video in youtube 
(Synchronize Active Directory to Qlik NPrinting - Qlik Tuesday Tips and Tricks)

And below my adsyncnprinting.config file :

  add key="url" value="xxx.xx.xx.xxx:389" />

  add key="domainName" value="mydomainname" />
  
  add key="rootDN" value="OU=NPrinting,DC=mydomainname,DC=com" />

  add key="syncBaseDN" value="DC=mydomainname,DC=com" />

  add key="searchFilter" value="(&amp;(objectCategory=group)(name=NP*))"/>
  
  add key="searchDeletedObjectsFilter" value="(&amp;(&amp;(objectClass=group)(lastKnownParent={0}))(isDeleted=TRUE))"/>

  add key="npUrl" value="https://mynprintingserver:4993" />

**Comment by bra1438** [comment]
I deleted all the code in "adsyncnprinting.config" and I still have the same problem !!!
I think the problem do not come from this file ....
HELP ME...

**Comment by bra1438** [comment]
now i have this error

Performing a full sync.
Processing Group: NPrinting_NewsStand User
API Error: Qlik.NPrinting.Rest.Client.Client.ApiException: Error calling RolesGe
t: {"message":"No HTTP resource was found that matches the request URI 'http://mynprintingserver:4996/api/v1/roles?rolename=NewsStand User'.","messageDetail":"No
route data was found for this request."}

**Comment by vus-qlik** [comment]
Do you have NPrinting version 17.4 or later?

**Comment by bra1438** [comment]
no, my version is 17.3.0.0.

why, is working only with the 17.4 or later ?

**Comment by vus-qlik** [comment]
these are new APIs added in version 17.4

**Comment by bra1438** [comment]
I upgrade NPrinting and is working
Thank you

**Comment by vus-qlik** [comment]
ok cool! Closing the issue then

**Comment by fdaqlik** [comment]
@vus-qlik I suggest you add the requirement of supported NP versions in the README.md.

**Comment by bra1438** [comment]
How to import users without group in AD ?
I change objectCategory in adsyncnprinting.config to user like this
add key="searchFilter" value="(&amp;(objectCategory=user)(name=usertest*))"/ ...
but not working ???

**Comment by vus-qlik** [comment]
Users can only be imported through Groups. You would have to define your logic to handle Users and  NP Roles.
