### ISSUE TITLE
Malformed request when Domainaccount isn't empty

### ISSUE THREAD

**Issue by kod-apa** [qlik-oss/nprinting-adsync#4]
### Description

I'm trying to to use the C# library for creating users in NPrinting. I can create users (UsersPost) from code as along as I don't set the Domainaccount field to something else than "". The same problem exists when I try to modify a user with UsersIdPut. 
### Steps to Reproduce
The following code example crashes

          ApiClient apiClient = NPrintingApiFactory.GetNPrintingApiClient("https://hostname:4993/");
          var userApi = new UsersApi(apiClient);

           UserRequest user = new UserRequest(Email: "example@example.com", 
                Domainaccount: "example",
                Username: "example",
                Enabled: true, 
                Password: "garbage", 
                Timezone: "CET",
                Locale: UserLocale.En);
            
            userApi.UsersPost(user);

##### Expected behavior
A user is created with the domainaccount field set

##### Actual behavior
An exception is thrown

Qlik.NPrinting.Rest.Client.Client.ApiException
  HResult=0x80131500
  Message=Error calling UsersPost: {"error":{"code":400,"message":"Malformed parameters"}}
  Source=Qlik.NPrinting.Rest.Client
  StackTrace:
   at Qlik.NPrinting.Rest.Client.Api.UsersApi.UsersPostWithHttpInfo(UserRequest userRequest) in C:\Users\kahe\Documents\src\nprinting-adsync\src\NPrintingRestClient\Api\UsersApi.cs:line 2173
   at Qlik.NPrinting.Rest.Client.Api.UsersApi.UsersPost(UserRequest userRequest) in C:\Users\kahe\Documents\src\nprinting-adsync\src\NPrintingRestClient\Api\UsersApi.cs:line 2115
   at Example.Example.Main() in C:\Users\kahe\Documents\Visual Studio 2017\Projects\Connect2NPrinting\Connect2NPrinting\Program.cs:line 104

##### Operating system where the nprinting-adsync is deployed
Windows 10 & .Net 4.7.1

##### NPrinting
Windows Server 2012R2 Standard, 4 cores 16GB ram

### Versions

* nprinting-adsync: latest according to git
* NPrinting: November 2017
* Operating system: Client Windows 10, Server Windows Server 2012R2 Standard, 4 cores 16GB ram

When I set the field Domainaccount to "" in the code example everything works as it is supposed to. But I need the domainaccount set to enable Windows login in NPrinting.

**Comment by vus-qlik** [comment]
NPrinting user APIs perform a validation on the "DomainAccount" provided throwing an error of "Malformed parameters" in case of failure. This field can be configured in adsyncnprinting.config file  (<add key="domainName" value="xxxx" />) with the correct NPrinting Windows domain.
