### ISSUE TITLE
ADSync to NPrinting if no E-mail information in AD  

### ISSUE THREAD

**Issue by jkfong93** [qlik-oss/nprinting-adsync#5]
### Description
Is there a way to sync AD to NPrinting if email information is not available in AD?

### Steps done
1. Configure the adsyncnprinting config file.
2. Build the batch file.
3. Run the ADSyncDemoApp.exe file in command prompt.
4. Restarting NPrinting Services.
5. AD is not sync to NPrinting User.

Attached are the screenshots on the steps above.
Note: AD do not have email information required by NPrinting.

##### Operating system where the nprinting-adsync is deployed
Windows Server 2012

##### NPrinting
NPrinting Server February release
![build](https://user-images.githubusercontent.com/26426418/37083622-006f4ab4-222b-11e8-9072-eb092ea09337.PNG)
![config](https://user-images.githubusercontent.com/26426418/37083626-0336236c-222b-11e8-8f6b-009df1c46fd1.PNG)
![exefile](https://user-images.githubusercontent.com/26426418/37083628-051abdd2-222b-11e8-8f54-513be1e4520b.PNG)
![get-ad](https://user-images.githubusercontent.com/26426418/37083631-071c01d6-222b-11e8-89ac-ecd402d856f6.PNG)
![refreshing_webconsole](https://user-images.githubusercontent.com/26426418/37083635-090d61ce-222b-11e8-9864-161ca91c1331.PNG)
![restarting_services](https://user-images.githubusercontent.com/26426418/37083638-0afecd74-222b-11e8-8962-f0aaf22ff53e.PNG)

**Comment by vus-qlik** [comment]
Currently the Email field is just used to check if the AD user being process is a new one or not in NPrinting
